language: node_js
node_js:
- '0.10'
notifications:
  hipchat:
    rooms:
      secure: f8gLKEAvrr+tUw7YvghsydK1RIf/Ipp6g0goUk/Wb5KnuHIhazmAuCgIEa/0TcQVwpXEEMPSzXtqc06Ygx4W319UQNHQF3WLXK07g3MNv11EypqyxkGEpkknLXFXgizD3m84qdbcnZ8UqJFRwMVkp57k+eJVzOKweWEm6c5Oesc=
